name: CI
on: [push]
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -cover ./...

  run:
    name: go run
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Iterator Pattern
      run: go run iterator-pattern/main.go

    - name: Adapter Pattern
      run: go run adapter-pattern/main.go

    - name: Template Method Pattern
      run: go run template-method-pattern/main.go

    - name: Factory Method Pattern
      run: go run factory-method-pattern/main.go

    - name: Singleton Pattern
      run: go run singleton-pattern/main.go
